### ISSUE TITLE
update k9s to latest version (0.27.4 as of May 2023)

### ISSUE THREAD

**Issue by SingingBush** [luminoso/fedora-copr-k9s#1]
Any chance of an update to k9s [0.27.4](https://github.com/derailed/k9s/releases/tag/v0.27.4)

**Comment by luminoso** [comment]
It is updated. Why you believe its not?

**Comment by SingingBush** [comment]
sorry my bad, I was fairly sure when I checked the version last it was older and the builds on https://copr.fedorainfracloud.org/coprs/luminoso/k9s/builds/ were showing that _0.25.18-1.fc34_ was the last successful version.
